service:
  internalPort: 8080

startupProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 80

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
